#server port
server:
    port: 4000

spring:
    profiles:
        default: local
    
    config:
        import:
            - security/application-db.yml
            - security/application-mail.yml
    
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB

#JWT Secret Key 설정
secret:
    key: ${jwt.secret.key}

#file upload path
file:
    path: C://Users//samsung//Desktop//kumoh_board_backend//kumoh_board_backend//fileUpload # 나중에 수정 필요
    url: http://localhost:4000/file/
