name: Code Review GPT

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Node.js 18 이상을 사용하는지 확인

      - name: Install dependencies
        run: npm install code-review-gpt

      - name: Run Code Review GPT
        run: npx code-review-gpt review --ci=github --model=gpt-4o --reviewType=changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}